{% set name = "vcpkg-tool" %}
{% set version = "2021-10-18" %}

package:
  name: {{ name|lower }}
  version: {{ version.replace('-', '.') }}

source:
  url: https://github.com/microsoft/vcpkg-tool/archive/refs/tags/{{ version }}.tar.gz
  sha256: 537c3f8345fcfb4887b41f89761aa3015fa8e725d0aa236c03747102c62e2a9a
  patches:
    - 158.patch
build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
    - cmake
  run:
    - ninja
    - cmake
    - curl
    - git
    - unzip  # [unix]
    - tar    # [unix]
    - 7zip   # [win]
  run_constrained:
    - vcpkg >2020.11

test:
  commands:
    - vcpkg --help || true             # [unix]
    - vcpkg.exe --help & exit 0        # [win]

about:
  home: https://github.com/microsoft/vcpkg
  license: MIT
  license_file: LICENSE.txt
  summary: C++ Library Manager for Windows, Linux, and MacOS

extra:
  recipe-maintainers:
    - wolfv
