{% set name = "vcpkg-tool" %}
{% set version = "2023-03-22" %}

package:
  name: {{ name|lower }}
  version: {{ version.replace('-', '.') }}

source:
  url: https://github.com/microsoft/vcpkg-tool/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2c199bf18531b7351a5b4f67989f8d83e0d2e640edb7f4094dfbe3f36ddc6023

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
    - cmake
  run:
    - ninja
    - cmake
    - curl
    - git
    - unzip  # [unix]
    - tar    # [unix]
    - 7zip   # [win]
  run_constrained:
    - vcpkg >2020.11

test:
  commands:
    - vcpkg --help || true             # [unix]
    - vcpkg.exe --help & exit 0        # [win]

about:
  home: https://github.com/microsoft/vcpkg
  license: MIT
  license_file: LICENSE.txt
  summary: C++ Library Manager for Windows, Linux, and MacOS

extra:
  recipe-maintainers:
    - wolfv
