{% set name = "vcpkg-tool" %}
{% set version = "2023-05-31" %}

package:
  name: {{ name|lower }}
  version: {{ version.replace('-', '.') }}

source:
  url: https://github.com/microsoft/vcpkg-tool/archive/refs/tags/{{ version }}.tar.gz
  sha256: b811df1a5ce4d7a29a16640b253ca8fd2e436337af89470ed562bb4b992b046f

build:
  number: 0
  script: bash %RECIPE_DIR%\build.sh  # [win]

requirements:
  build:
    - m2-bash  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
    - cmake
  run:
    - ninja
    - cmake
    - curl
    - git
    - unzip  # [unix]
    - tar    # [unix]
    - 7zip   # [win]
  run_constrained:
    - vcpkg >2020.11

test:
  commands:
    - vcpkg --version                                 # [unix]
    - vcpkg.exe --version                             # [win]

about:
  home: https://github.com/microsoft/vcpkg-tool
  license: MIT
  license_file: LICENSE.txt
  summary: C++ Library Manager for Windows, Linux, and MacOS

extra:
  recipe-maintainers:
    - wolfv
